my_tokens = ['/td', '/tr', '/th', '/bold', '/italic', '/sup', '/xref', '/h4', '/head', '/table', '/body', '/html', '/tbody',
             '/thead', '/sub', '/p', '/mml:mo', '/mml:mi', '/mml:mrow', '/mml:mn', '/mml:math', '/inline-formula', '/ext-link',
             '/colgroup', '/list-item', '/tex-math', '/alternatives', '/underline', '/named-content', '/mml:msub', '/list', '/mml:mtext',
             '/mml:msup', '/monospace', '/mml:msubsup', '/sc', '/label', '/mml:mover', '/mml:mfrac', '/mml:mstyle', '/styled-content', '/mml:mfenced',
             '/mml:mtd', '/mml:mtr', '/abbrev', '/mml:munder', '/uri', '/mml:mtable', '/disp-formula', '/mml:semantics', '/mml:msqrt', '/sans-serif',
             '/mml:munderover', '/alt-text', '/inline-graphic', '/mml:annotation', '/mml:mpadded', '/tfoot', '/private-char', '/strike', '/mml:mmultiscripts',
             '/overline', '/chem-struct', '/preformat', '/email', '/roman', '/x', '/glyph-data', '/mml:menclose', '/chem-struct-wrap', '/graphic',
             '/mml:mroot', '/code', '/disp-quote', '/title', '/mml:mphantom', '/copyright-holder', '/permissions', '/disp-formula-group', '/', '/fig',
             '/funding-source', '/tb', '/= 1% vs.', 'td', 'tr', 'th', 'bold', 'italic', 'sup', 'xref', 'h4', 'head', 'table', 'body', 'html', 'tbody',
             'thead', 'sub', 'p', 'mml:mo', 'mml:mi', 'mml:mrow', 'mml:mn', 'mml:math', 'inline-formula', 'ext-link', 'colgroup', 'list-item', 'tex-math',
             'alternatives', 'underline', 'named-content', 'mml:msub', 'list', 'mml:mtext', 'mml:msup', 'monospace', 'mml:msubsup', 'sc', 'label', 'mml:mover',
             'mml:mfrac', 'mml:mstyle', 'styled-content', 'mml:mfenced', 'mml:mtd', 'mml:mtr', 'abbrev', 'mml:munder', 'uri', 'mml:mtable', 'disp-formula',
             'mml:semantics', 'mml:msqrt', 'sans-serif', 'mml:munderover', 'alt-text', 'inline-graphic', 'mml:annotation', 'mml:mpadded', 'tfoot',
             'private-char', 'strike', 'mml:mmultiscripts', 'overline', 'chem-struct_preformat', 'email', 'roman', 'x', 'glyph-data', 'mml:menclose',
             'chem-struct-wrap', 'graphic', 'mml:mroot', 'code', 'disp-quote', 'title', 'mml:mphantom', 'copyright-holder', 'permissions', 'disp-formula-group',
             'fig', 'funding-source', 'tb', '= 1% vs.', '!DOCTYPE', '''align="left"''']


my_tokens2= ["<" + i for i in my_tokens]
my_tokens3= [i + ">"for i in my_tokens2]

my_tokens3= ['</td>', '</tr>', '</th>', '</bold>', '</italic>', '</sup>', '</xref>', '</h4>', '</head>', '</table>', '</body>', '</html>', '</tbody>', '</thead>', '</sub>', '</p>', '</mml:mo>', '</mml:mi>', '</mml:mrow>', '</mml:mn>', '</mml:math>', '</inline-formula>', '</ext-link>', '</colgroup>', '</list-item>', '</tex-math>', '</alternatives>', '</underline>', '</named-content>', '</mml:msub>', '</list>', '</mml:mtext>', '</mml:msup>', '</monospace>', '</mml:msubsup>', '</sc>', '</label>', '</mml:mover>', '</mml:mfrac>', '</mml:mstyle>', '</styled-content>', '</mml:mfenced>', '</mml:mtd>', '</mml:mtr>', '</abbrev>', '</mml:munder>', '</uri>', '</mml:mtable>', '</disp-formula>', '</mml:semantics>', '</mml:msqrt>', '</sans-serif>', '</mml:munderover>', '</alt-text>', '</inline-graphic>', '</mml:annotation>', '</mml:mpadded>', '</tfoot>', '</private-char>', '</strike>', '</mml:mmultiscripts>', '</overline>', '</chem-struct>', '</preformat>', '</email>', '</roman>', '</x>', '</glyph-data>', '</mml:menclose>', '</chem-struct-wrap>', '</graphic>', '</mml:mroot>', '</code>', '</disp-quote>', '</title>', '</mml:mphantom>', '</copyright-holder>', '</permissions>', '</disp-formula-group>', '</>', '</fig>', '</funding-source>', '</tb>', '</= 1% vs.>', '<td>', '<tr>', '<th>', '<bold>', '<italic>', '<sup>', '<xref>', '<h4>', '<head>', '<table>', '<body>', '<html>', '<tbody>', '<thead>', '<sub>', '<p>', '<mml:mo>', '<mml:mi>', '<mml:mrow>', '<mml:mn>', '<mml:math>', '<inline-formula>', '<ext-link>', '<colgroup>', '<list-item>', '<tex-math>', '<alternatives>', '<underline>', '<named-content>', '<mml:msub>', '<list>', '<mml:mtext>', '<mml:msup>', '<monospace>', '<mml:msubsup>', '<sc>', '<label>', '<mml:mover>', '<mml:mfrac>', '<mml:mstyle>', '<styled-content>', '<mml:mfenced>', '<mml:mtd>', '<mml:mtr>', '<abbrev>', '<mml:munder>', '<uri>', '<mml:mtable>', '<disp-formula>', '<mml:semantics>', '<mml:msqrt>', '<sans-serif>', '<mml:munderover>', '<alt-text>', '<inline-graphic>', '<mml:annotation>', '<mml:mpadded>', '<tfoot>', '<private-char>', '<strike>', '<mml:mmultiscripts>', '<overline>', '<chem-struct_preformat>', '<email>', '<roman>', '<x>', '<glyph-data>', '<mml:menclose>', '<chem-struct-wrap>', '<graphic>', '<mml:mroot>', '<code>', '<disp-quote>', '<title>', '<mml:mphantom>', '<copyright-holder>', '<permissions>', '<disp-formula-group>', '<fig>', '<funding-source>', '<tb>', '<= 1% vs.>', '<!DOCTYPE>', '<align="left">']
